version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
    - type: bind
      source: ./nginx/default.conf
      target: /etc/nginx/conf.d/default.conf
    - type: bind
      source: ./nginx/.htpasswd
      target: /etc/nginx/.htpasswd
